"""create inference log table

Revision ID: 96dacbb8a2c0
Revises: 
Create Date: 2026-06-11 12:15:32.488467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96dacbb8a2c0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inference_log', sa.Column('shap_values_json', sa.Text(), nullable=True), schema='app')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inference_log', 'shap_values_json', schema='app')
    # ### end Alembic commands ###
